In [1]:
# execute to import notebook styling for tables and width etc.
from IPython.core.display import HTML
import urllib.request
response = urllib.request.urlopen(
    'https://raw.githubusercontent.com/DataScienceUWL/DS775v2/master/ds755.css'
)
HTML(response.read().decode("utf-8"))

# Transportation with Capacity Constraint

In [12]:
# using openpyxl
from openpyxl import load_workbook
wb = load_workbook(filename='data/transp_prob_1.xlsx', data_only=True)
sheet = wb.active

# specify upper left and lower right cells, returns a list or list of lists representing rows
def read_range(sheet, begin, end):
    table = sheet[begin:end]
    height = len(table)
    width = len(table[0])
    if height == 1 or width == 1:
        # for a single row or column produce a list
        tmp = [cell.value for row in table for cell in row]
    else:
        # for an array of cells produces a list of row lists
        tmp = [[cell.value for cell in row] for row in table]
    return (tmp)


warehouses = read_range(sheet, 'A3', 'A5')
stores = read_range(sheet, 'B3', 'B22')
wares_stores = {(w,s) for [w,s] in read_range(sheet,'D3','E31')}
capacity_dict = {(w,s):cost for [w,s,cost] in read_range(sheet,'D3','F31')}
cost_dict = {(w,s):cap for [w,s,cost,cap] in read_range(sheet,'D3','G31')}
supply_dict = { w:q for [w,q] in read_range(sheet,'I3','J5')}
demand_dict = { s:q for [s,q] in read_range(sheet,'L3','M22')}

# throw an error if total supply and demand do not match
assert (sum(supply_dict.values()) == sum(demand_dict.values()))

from pyomo.environ import *

model = ConcreteModel()

model.transp = Var(wares_stores, domain=NonNegativeReals)

model.total_cost = Objective(expr=sum(cost_dict[w, s] * model.transp[w, s]
                                      for (w, s) in wares_stores),
                             sense=minimize)

model.supply_ct = ConstraintList()
for w in warehouses:
    model.supply_ct.add(
        sum(model.transp[w, s] for s in stores
            if (w, s) in wares_stores) == supply_dict[w])

model.demand_ct = ConstraintList()
for s in stores:
    model.demand_ct.add(
        sum(model.transp[w, s] for w in warehouses
            if (w, s) in wares_stores) == demand_dict[s])


model.capacity_ct = ConstraintList()
for (w,s) in wares_stores:
    model.capacity_ct.add( model.transp[w, s] <= capacity_dict[w, s] )

# solve and display
solver = SolverFactory('glpk')
solver.solve(model)

# convert model.hrs into a Pandas data frame for nicer display
import pandas as pd
transp = pd.DataFrame(0, index=warehouses, columns=stores)
for (w, s) in wares_stores:
    transp.loc[w, s] = model.transp[w, s].value

# display
import babel.numbers as numbers  # needed to display as currency
print("The minimum total transportation cost = ",
      numbers.format_currency(model.total_cost(), 'USD', locale='en_US'))
print("\nThe transported amounts: ")
transp

The minimum total transportation cost =  $29,827.00

The transported amounts:

,sA,sB,sC,sD,sE,sF,sG,sH,sI,sJ,sK,sL,sM,sN,sO,sP,sQ,sR,sS,sT
wA,173.0,103.0,110.0,121.0,148.0,145.0,100.0,23.0,100.0,77.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wB,0.0,0.0,0.0,0.0,0.0,0.0,54.0,100.0,65.0,92.0,175.0,82.0,100.0,100.0,32.0,100.0,0.0,0.0,0.0,0.0
wC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,83.0,84.0,65.0,100.0,83.0,146.0,142.0,175.0,122.0

# Shipping Wood to Market

In [42]:
sources = ['s1', 's2', 's3']
supply = dict(zip(sources, [15, 20, 15]))

markets = ['m1', 'm2', 'm3', 'm4', 'm5']
demand = dict(zip(markets, [11, 12, 9, 10, 8]))

usc_rail = [[61, 72, 45, 55, 66], [69, 78, 60, 49, 56], [59, 66, 63, 61, 47]]

bigM = 10000
usc_ships = [[31, 38, 24, bigM, 35], [36, 43, 28, 24, 31],
             [bigM, 33, 36, 32, 26]]
invest_ships = [[275, 303, 238, bigM, 285], [293, 318, 270, 250, 265],
                [bigM, 283, 275, 268, 240]]

usc_tot_ships = [[
    usc_ships[i][j] + 0.1 * invest_ships[i][j] for j in range(5)
] for i in range(3)]

usc_rail_or_ships = [[
    min(usc_tot_ships[i][j], usc_rail[i][j]) for j in range(5)
] for i in range(3)]

labels_R_or_S = pd.DataFrame("Rail",columns=markets,index=sources)

for s in range(3):
    for m in range(5):
        if usc_tot_ships[s][m] < usc_rail[s][m]:
            labels_R_or_S.iloc[s,m] = "Ships"

In [44]:
from pyomo.environ import *

def wood_shipping(usc):
    unit_ship_cost = {
        sources[s]: {markets[m]: usc[s][m]
                     for m in range(len(markets))}
        for s in range(len(sources))
    }

    model = ConcreteModel()

    model.transp = Var(sources, markets, domain=NonNegativeReals)

    model.total_cost = Objective(expr=sum(unit_ship_cost[s][m] *
                                          model.transp[s, m] for s in sources
                                          for m in markets),
                                 sense=minimize)


    model.supply_ct = ConstraintList()
    for s in sources:
        model.supply_ct.add(
            sum(model.transp[s, m] for m in markets) == supply[s])

    model.demand_ct = ConstraintList()
    for m in markets:
        model.demand_ct.add(
            sum(model.transp[s, m] for s in sources) == demand[m])

    # solve and display
    solver = SolverFactory('glpk')
    solver.solve(model)

    # display solution
    import babel.numbers as numbers  # needed to display as currency
    print("Minimum Total Cost = ",
          numbers.format_currency(model.total_cost()*1.e3, 'USD', locale='en_US'))
    # put amounts in dataframe for nicer display
    import pandas as pd
    dvars = pd.DataFrame([[model.transp[s, m]() for m in markets]
                      for s in sources],
                     index=sources,
                     columns=markets)
    print("Millions of sq. ft. to ship souce to market:")
    from IPython.display import display, HTML
    display(dvars)
    
print('By rail:')
wood_shipping(usc_rail)

print('By ship:')
wood_shipping(usc_tot_ships)

print('Using cheapest rail or ship:')
wood_shipping(usc_rail_or_ships)
print('Which form of transport to use on each route:')
labels_R_or_S

By rail:
Minimum Total Cost =  $2,816,000.00
Millions of sq. ft. to ship souce to market:

     m1    m2   m3    m4   m5
s1  6.0   0.0  9.0   0.0  0.0
s2  2.0   0.0  0.0  10.0  8.0
s3  3.0  12.0  0.0   0.0  0.0

By ship:
Minimum Total Cost =  $2,770,800.00
Millions of sq. ft. to ship souce to market:

     m1    m2   m3    m4   m5
s1  6.0   0.0  9.0   0.0  0.0
s2  5.0   0.0  0.0  10.0  5.0
s3  0.0  12.0  0.0   0.0  3.0

Using cheapest rail or ship:
Minimum Total Cost =  $2,729,100.00
Millions of sq. ft. to ship souce to market:

     m1    m2   m3    m4   m5
s1  6.0   0.0  9.0   0.0  0.0
s2  5.0   0.0  0.0  10.0  5.0
s3  0.0  12.0  0.0   0.0  3.0

Which form of transport to use on each route:

       m1     m2     m3     m4     m5
s1  Ships  Ships   Rail   Rail  Ships
s2  Ships  Ships  Ships   Rail   Rail
s3   Rail  Ships   Rail  Ships   Rail

# Transporting Multiple Products

In [4]:
#############################
# Homework Problem 3 - A more complex transportation problem
#############################

# using openpyxl
from openpyxl import load_workbook
wb = load_workbook(filename='data/transp_prob3.xlsx', data_only=True)
sheet = wb.active


# specify upper left and lower right cells, returns a list or list of lists representing rows
# for a single value read_range(sheet,'A11')
# for a list of values in a column or row read_range(sheet,'A11','N11')
# for nested lists of values (array-like) read_range(sheet,'A11','D23')
def read_range(sheet, begin, *argv):
    if len(argv) > 0:
        end = argv[0]
        table = sheet[begin:end]
        height = len(table)
        width = len(table[0])
        if height == 1 or width == 1:
            # for a single row or column produce a list
            tmp = [cell.value for row in table for cell in row]
        else:
            # for an array of cells produces a list of row lists
            tmp = [[cell.value for cell in row] for row in table]
    else:
        tmp = sheet[begin].value
    return (tmp)


#get basic data
factories = read_range(sheet, 'A2', 'A6')
warehouses = read_range(sheet, 'B2', 'B11')
stores = read_range(sheet, 'C2', 'C21')
products = read_range(sheet, 'D2', 'D6')

capacityFW = read_range(sheet, 'E2')
capacityWS = read_range(sheet, 'E5')
maxStorage = read_range(sheet, 'E8')

# all feasible product-factory-warehouse combinations
pfwroutes = {(p, f, w)
             for [p, f, w] in read_range(sheet, 'G3', 'I71')
             }  #read_range(sheet, 'G3', 'I71')
fwcosts = {(p, f, w): c
           for [p, f, w, c] in read_range(sheet, 'G3', 'J71')
           }  #read_range(sheet, 'G3', 'J71')

#some constraints require that we have f-w without p.
fwroutes = {(f, w) for [f, w] in read_range(sheet, 'H3', 'I71')}

# all feasible product-warehouse-store combinations
pwsroutes = {(p, w, s)
             for [p, w, s] in read_range(sheet, 'L3', 'N202')
             }  #read_range(sheet, 'L3', 'N202')
wscosts = {(p, w, s): c
           for [p, w, s, c] in read_range(sheet, 'L3', 'O202')
           }  #read_range(sheet, 'L3', 'O202')

#some constraints require that we have w-s without p
wsroutes = {(w, s) for [w, s] in read_range(sheet, 'M3', 'N202')}

#supply and demand
supply = {(p, f): q for [p, f, q] in read_range(sheet, 'Q3', 'S15')}
demand = {(p, s): q for [p, s, q] in read_range(sheet, 'U3', 'W102')}

from pyomo.environ import *

model = ConcreteModel()

#we have 2 sets of decision variables
model.pfwroutes = Var(pfwroutes, domain=NonNegativeReals
                      )  # one decions variable for each feasible p-f-w combo
model.pwsroutes = Var(pwsroutes, domain=NonNegativeReals
                      )  # one decions variable for each feasible p-w-s combo

#combined for a single objective function
model.total_cost = Objective(
    expr=sum((fwcosts[p, f, w] * model.pfwroutes[p, f, w]
              for (p, f, w) in pfwroutes)) +
    sum(wscosts[p, w, s] * model.pwsroutes[p, w, s]
        for (p, w, s) in pwsroutes))

#constraints
#the amount of each product at each factory must match the supply amount
model.supply_ct = ConstraintList()
for (p, f) in supply:
    model.supply_ct.add(
        sum(model.pfwroutes[p, f, w] for w in warehouses
            if (p, f, w) in pfwroutes) == supply[p, f])

#model.supply_ct.pprint()
#the amount of each product delivered to each store must match the demand amount
model.demand_ct = ConstraintList()
for (p, s) in demand:
    model.demand_ct.add(
        sum(model.pwsroutes[p, w, s] for w in warehouses
            if (p, w, s) in pwsroutes) == demand[p, s])

#model.demand_ct.pprint()
#the amount of each product shipped to each warehouse must be the same as the amount of each product shipped from each warehouse
model.inout_ct = ConstraintList()
for w in warehouses:
    for p in products:
        # The total shipped in minus the total shipped out of each warehouse must equal 0
        model.inout_ct.add(
            (sum(model.pfwroutes[p, f, w]
                 for f in factories if (p, f, w) in pfwroutes)) -
            (sum(model.pwsroutes[p, w, s]
                 for s in stores if (p, w, s) in pwsroutes)) == 0)

#the total (summed) amount of all products at each warehouse must be  ≤  MaxStorage
model.maxstorage_ct = ConstraintList()
for w in warehouses:
    # add up all product at each warehouse
    model.maxstorage_ct.add(
        sum(model.pfwroutes[p, f, w] for p in products
            for f in factories if (p, f, w) in pfwroutes) <= maxStorage)

#the total (summed) amount of all products shipped from each factory to each warehouse must be  ≤  CapacityFW
model.capacityfw_ct = ConstraintList()
for f in factories:
    for w in warehouses:
        if (f, w) in fwroutes:
            # add up all product at each warehouse
            model.capacityfw_ct.add(
                sum(model.pfwroutes[p, f, w]
                    for p in products if (p, f, w) in pfwroutes) <= capacityFW)

#the total (summed) amount of all products shipped from each warehouse to each store must be  ≤  CapacityWS
model.capacityws_ct = ConstraintList()
for (w, s) in wsroutes:
    # add up all product at each warehouse
    model.capacityws_ct.add(
        sum(model.pwsroutes[p, w, s]
            for p in products if (p, w, s) in pwsroutes) <= capacityWS)

# solve and display
solver = SolverFactory('glpk')
solver.solve(model)

# display
# convert model.pwf into a Pandas data frame for nicer display
import pandas as pd


def printRoutes(product, from_var, to_var, values_var):
    transp = pd.DataFrame(0, index=from_var, columns=to_var)
    for (p, w, s) in values_var:
        if p == product:
            transp.loc[w, s] = values_var[product, w, s].value
    return transp


# display
import babel.numbers as numbers  # needed to display as currency
print("The minimum total transportation cost = ",
      numbers.format_currency(model.total_cost(), 'USD', locale='en_US'))

from IPython.display import display
for p in products:
    print(
        "\nThe transported amounts of product {0} from factory to warehouse:".
        format(p))
    display(printRoutes(p, factories, warehouses, model.pfwroutes))

    print("\nThe transported amounts of product {0} from warehouse to store:".
          format(p))
    display(printRoutes(p, warehouses, stores, model.pwsroutes))

The minimum total transportation cost =  $45,360.00

The transported amounts of product pA from factory to warehouse:

       wA     wB     wC     wD     wE     wF     wG     wH     wI     wJ
fA  240.0  220.0  130.0  110.0    0.0    0.0    0.0    0.0    0.0    0.0
fB    0.0    0.0    0.0  120.0  290.0  150.0    0.0    0.0    0.0    0.0
fC    0.0    0.0    0.0    0.0   80.0   30.0  170.0  180.0  120.0  220.0
fD    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
fE    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0

The transported amounts of product pA from warehouse to store:

,sA,sB,sC,sD,sE,sF,sG,sH,sI,sJ,sK,sL,sM,sN,sO,sP,sQ,sR,sS,sT
wA,150.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wB,0.0,0.0,80.0,140.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wC,0.0,0.0,0.0,0.0,60.0,70.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wD,0.0,0.0,0.0,0.0,0.0,0.0,110.0,120.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,90.0,200.0,0.0,80.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,180.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,110.0,0.0,0.0,0.0,0.0,0.0,0.0
wH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,120.0,60.0,0.0,0.0,0.0,0.0
wI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,70.0,50.0,0.0,0.0
wJ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,120.0

The transported amounts of product pB from factory to warehouse:

       wA     wB     wC     wD     wE     wF    wG     wH     wI     wJ
fA  260.0  200.0    0.0   40.0    0.0    0.0   0.0    0.0    0.0    0.0
fB    0.0    0.0  150.0  220.0  530.0  100.0   0.0    0.0    0.0    0.0
fC    0.0    0.0    0.0    0.0    0.0    0.0  60.0  160.0  140.0  240.0
fD    0.0    0.0    0.0    0.0    0.0    0.0   0.0    0.0    0.0    0.0
fE    0.0    0.0    0.0    0.0    0.0    0.0   0.0    0.0    0.0    0.0

The transported amounts of product pB from warehouse to store:

,sA,sB,sC,sD,sE,sF,sG,sH,sI,sJ,sK,sL,sM,sN,sO,sP,sQ,sR,sS,sT
wA,160.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wB,0.0,0.0,70.0,130.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wC,0.0,0.0,0.0,0.0,70.0,80.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wD,0.0,0.0,0.0,0.0,0.0,0.0,100.0,110.0,0.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,160.0,180.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,50.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0
wG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0
wH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,110.0,50.0,0.0,0.0,0.0,0.0
wI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,80.0,0.0,0.0
wJ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,110.0,130.0

The transported amounts of product pC from factory to warehouse:

      wA     wB    wC     wD     wE   wF    wG    wH    wI     wJ
fA  10.0  100.0  70.0  220.0    0.0  0.0   0.0   0.0   0.0    0.0
fB   0.0    0.0   0.0    0.0  180.0  0.0  80.0  80.0  70.0  260.0
fC   0.0    0.0   0.0    0.0    0.0  0.0   0.0   0.0   0.0    0.0
fD   0.0    0.0   0.0    0.0    0.0  0.0   0.0   0.0   0.0    0.0
fE   0.0    0.0   0.0    0.0    0.0  0.0   0.0   0.0   0.0    0.0

The transported amounts of product pC from warehouse to store:

,sA,sB,sC,sD,sE,sF,sG,sH,sI,sJ,sK,sL,sM,sN,sO,sP,sQ,sR,sS,sT
wA,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wB,0.0,0.0,30.0,70.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wC,0.0,0.0,0.0,0.0,30.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wD,0.0,0.0,0.0,0.0,0.0,0.0,50.0,60.0,0.0,110.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,0.0,100.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0
wH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,20.0,0.0,0.0,0.0,0.0
wI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,40.0,0.0,0.0
wJ,80.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,70.0

The transported amounts of product pD from factory to warehouse:

     wA    wB    wC    wD     wE   wF    wG    wH    wI     wJ
fA  0.0   0.0   0.0   0.0    0.0  0.0   0.0   0.0   0.0    0.0
fB  0.0   0.0   0.0   0.0    0.0  0.0   0.0   0.0   0.0    0.0
fC  0.0   0.0   0.0   0.0    0.0  0.0   0.0   0.0   0.0    0.0
fD  0.0  60.0  30.0  70.0  140.0  0.0   0.0   0.0   0.0    0.0
fE  0.0   0.0   0.0   0.0    0.0  0.0  50.0  50.0  40.0  140.0

The transported amounts of product pD from warehouse to store:

,sA,sB,sC,sD,sE,sF,sG,sH,sI,sJ,sK,sL,sM,sN,sO,sP,sQ,sR,sS,sT
wA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wB,0.0,0.0,20.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wC,0.0,0.0,0.0,0.0,10.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wD,0.0,0.0,0.0,0.0,0.0,0.0,30.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,50.0,50.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0
wH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,10.0,0.0,0.0,0.0,0.0
wI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,20.0,0.0,0.0
wJ,40.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,60.0

The transported amounts of product pE from factory to warehouse:

       wA     wB     wC     wD     wE   wF     wG     wH     wI     wJ
fA    0.0    0.0    0.0    0.0    0.0  0.0    0.0    0.0    0.0    0.0
fB    0.0    0.0    0.0    0.0    0.0  0.0    0.0    0.0    0.0    0.0
fC  420.0  450.0  530.0    0.0    0.0  0.0    0.0    0.0    0.0    0.0
fD    0.0    0.0    0.0  210.0  790.0  0.0    0.0    0.0    0.0    0.0
fE    0.0    0.0    0.0    0.0  290.0  0.0  340.0  380.0  230.0  520.0

The transported amounts of product pE from warehouse to store:

,sA,sB,sC,sD,sE,sF,sG,sH,sI,sJ,sK,sL,sM,sN,sO,sP,sQ,sR,sS,sT
wA,220.0,200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wB,0.0,0.0,150.0,300.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wC,0.0,0.0,0.0,0.0,140.0,150.0,240.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,210.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,180.0,390.0,360.0,150.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,140.0,200.0,0.0,0.0,0.0,0.0,0.0,0.0
wH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,250.0,130.0,0.0,0.0,0.0,0.0
wI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,130.0,100.0,0.0,0.0
wJ,80.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,210.0,230.0

Another way to approach the problem is think of the amounts at the warehouses as being unknowns and introducing variables for those values.  These then form a demand constraint for the FW routes and a supply constraint for the WS routes.

In [14]:
#############################
# Homework Problem 3 - A more complex transportation problem
# use extra variables for amounts at warehouses
#############################

# using openpyxl
from openpyxl import load_workbook
wb = load_workbook(filename='data/transp_prob3.xlsx', data_only=True)
sheet = wb.active


# specify upper left and lower right cells, returns a list or list of lists representing rows
# for a single value read_range(sheet,'A11')
# for a list of values in a column or row read_range(sheet,'A11','N11')
# for nested lists of values (array-like) read_range(sheet,'A11','D23')
def read_range(sheet, begin, *argv):
    if len(argv) > 0:
        end = argv[0]
        table = sheet[begin:end]
        height = len(table)
        width = len(table[0])
        if height == 1 or width == 1:
            # for a single row or column produce a list
            tmp = [cell.value for row in table for cell in row]
        else:
            # for an array of cells produces a list of row lists
            tmp = [[cell.value for cell in row] for row in table]
    else:
        tmp = sheet[begin].value
    return (tmp)


#get basic data
factories = read_range(sheet, 'A2', 'A6')
warehouses = read_range(sheet, 'B2', 'B11')
stores = read_range(sheet, 'C2', 'C21')
products = read_range(sheet, 'D2', 'D6')

capacityFW = read_range(sheet, 'E2')
capacityWS = read_range(sheet, 'E5')
maxStorage = read_range(sheet, 'E8')

# all feasible product-factory-warehouse combinations
pfwroutes = {(p, f, w)
             for [p, f, w] in read_range(sheet, 'G3', 'I71')
             }  #read_range(sheet, 'G3', 'I71')
fwcosts = {(p, f, w): c
           for [p, f, w, c] in read_range(sheet, 'G3', 'J71')
           }  #read_range(sheet, 'G3', 'J71')

#some constraints require that we have f-w without p.
fwroutes = {(f, w) for [f, w] in read_range(sheet, 'H3', 'I71')}

# all feasible product-warehouse-store combinations
pwsroutes = {(p, w, s)
             for [p, w, s] in read_range(sheet, 'L3', 'N202')
             }  #read_range(sheet, 'L3', 'N202')
wscosts = {(p, w, s): c
           for [p, w, s, c] in read_range(sheet, 'L3', 'O202')
           }  #read_range(sheet, 'L3', 'O202')
products_wares = {(p, w) for (p, w, s) in pwsroutes}

#some constraints require that we have w-s without p
wsroutes = {(w, s) for [w, s] in read_range(sheet, 'M3', 'N202')}

#supply and demand
supply = {(p, f): q for [p, f, q] in read_range(sheet, 'Q3', 'S15')}
demand = {(p, s): q for [p, s, q] in read_range(sheet, 'U3', 'W102')}

from pyomo.environ import *

model = ConcreteModel()

#we have 2 sets of decision variables
model.pfwroutes = Var(pfwroutes, domain=NonNegativeReals
                      )  # one decions variable for each feasible p-f-w combo
model.pwsroutes = Var(pwsroutes, domain=NonNegativeReals
                      )  # one decions variable for each feasible p-w-s combo
model.pwstore = Var(products_wares, domain=NonNegativeReals)

#combined for a single objective function
model.total_cost = Objective(
    expr=sum((fwcosts[p, f, w] * model.pfwroutes[p, f, w]
              for (p, f, w) in pfwroutes)) +
    sum(wscosts[p, w, s] * model.pwsroutes[p, w, s]
        for (p, w, s) in pwsroutes))

#constraints
#the amount of each product at each factory must match the supply amount
model.supply_f_ct = ConstraintList()
for (p, f) in supply:
    model.supply_f_ct.add(
        sum(model.pfwroutes[p, f, w] for w in warehouses
            if (p, f, w) in pfwroutes) == supply[p, f])

model.demand_w_ct = ConstraintList()
for (p, w) in products_wares:
    model.demand_w_ct.add(
        sum(model.pfwroutes[p, f, w] for f in factories
            if (p, f, w) in pfwroutes) == model.pwstore[p, w])
    
model.supply_w_ct = ConstraintList()
for (p, w) in products_wares:
    model.supply_w_ct.add(
        sum(model.pwsroutes[p, w, s] for s in stores
            if (p, w, s) in pwsroutes) == model.pwstore[p, w])

#the amount of each product delivered to each store must match the demand amount
model.demand_s_ct = ConstraintList()
for (p, s) in demand:
    model.demand_s_ct.add(
        sum(model.pwsroutes[p, w, s] for w in warehouses
            if (p, w, s) in pwsroutes) == demand[p, s])


#the total (summed) amount of all products at each warehouse must be  ≤  MaxStorage
model.maxstorage_ct = ConstraintList()
for w in warehouses:
    # add up all product at each warehouse
    model.maxstorage_ct.add(
        sum(model.pwstore[p,w] for p in products ) <= maxStorage) 

#the total (summed) amount of all products shipped from each factory to each warehouse must be  ≤  CapacityFW
model.capacityfw_ct = ConstraintList()
for (f,w) in fwroutes:
    # add up all product at each warehouse
    model.capacityfw_ct.add(
        sum(model.pfwroutes[p, f, w]
            for p in products if (p, f, w) in pfwroutes) <= capacityFW)

#the total (summed) amount of all products shipped from each warehouse to each store must be  ≤  CapacityWS
model.capacityws_ct = ConstraintList()
for (w, s) in wsroutes:
    # add up all product at each warehouse
    model.capacityws_ct.add(
        sum(model.pwsroutes[p, w, s]
            for p in products if (p, w, s) in pwsroutes) <= capacityWS)

# solve and display
solver = SolverFactory('glpk')
solver.solve(model)

# display
# convert model.pwf into a Pandas data frame for nicer display
import pandas as pd


def printRoutes(product, from_var, to_var, values_var):
    transp = pd.DataFrame(0, index=from_var, columns=to_var)
    for (p, w, s) in values_var:
        if p == product:
            transp.loc[w, s] = values_var[product, w, s].value
    return transp


# display
import babel.numbers as numbers  # needed to display as currency
print("The minimum total transportation cost = ",
      numbers.format_currency(model.total_cost(), 'USD', locale='en_US'))

from IPython.display import display
for p in products:
    print(
        "\nThe transported amounts of product {0} from factory to warehouse:".
        format(p))
    display(printRoutes(p, factories, warehouses, model.pfwroutes))

    print("\nThe transported amounts of product {0} from warehouse to store:".
          format(p))
    display(printRoutes(p, warehouses, stores, model.pwsroutes))

The minimum total transportation cost =  $45,360.00

The transported amounts of product pA from factory to warehouse:

       wA     wB     wC     wD     wE     wF     wG     wH     wI     wJ
fA  240.0  220.0  130.0  110.0    0.0    0.0    0.0    0.0    0.0    0.0
fB    0.0    0.0    0.0  120.0  290.0  150.0    0.0    0.0    0.0    0.0
fC    0.0    0.0    0.0    0.0   80.0   30.0  170.0  180.0  120.0  220.0
fD    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0
fE    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0

The transported amounts of product pA from warehouse to store:

,sA,sB,sC,sD,sE,sF,sG,sH,sI,sJ,sK,sL,sM,sN,sO,sP,sQ,sR,sS,sT
wA,150.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wB,0.0,0.0,80.0,140.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wC,0.0,0.0,0.0,0.0,60.0,70.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wD,0.0,0.0,0.0,0.0,0.0,0.0,110.0,120.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,90.0,200.0,0.0,80.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,180.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,110.0,0.0,0.0,0.0,0.0,0.0,0.0
wH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,120.0,60.0,0.0,0.0,0.0,0.0
wI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,70.0,50.0,0.0,0.0
wJ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,120.0

The transported amounts of product pB from factory to warehouse:

       wA     wB     wC     wD     wE     wF    wG     wH     wI     wJ
fA  260.0  200.0    0.0   40.0    0.0    0.0   0.0    0.0    0.0    0.0
fB    0.0    0.0  150.0  220.0  530.0  100.0   0.0    0.0    0.0    0.0
fC    0.0    0.0    0.0    0.0    0.0    0.0  60.0  160.0  140.0  240.0
fD    0.0    0.0    0.0    0.0    0.0    0.0   0.0    0.0    0.0    0.0
fE    0.0    0.0    0.0    0.0    0.0    0.0   0.0    0.0    0.0    0.0

The transported amounts of product pB from warehouse to store:

,sA,sB,sC,sD,sE,sF,sG,sH,sI,sJ,sK,sL,sM,sN,sO,sP,sQ,sR,sS,sT
wA,160.0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wB,0.0,0.0,70.0,130.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wC,0.0,0.0,0.0,0.0,70.0,80.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wD,0.0,0.0,0.0,0.0,0.0,0.0,100.0,110.0,0.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,160.0,180.0,90.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,0.0,50.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0
wG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,0.0,0.0,0.0,0.0,0.0,0.0
wH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,110.0,50.0,0.0,0.0,0.0,0.0
wI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,80.0,0.0,0.0
wJ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,110.0,130.0

The transported amounts of product pC from factory to warehouse:

      wA     wB    wC     wD     wE   wF    wG    wH    wI     wJ
fA  10.0  100.0  70.0  220.0    0.0  0.0   0.0   0.0   0.0    0.0
fB   0.0    0.0   0.0    0.0  180.0  0.0  80.0  80.0  70.0  260.0
fC   0.0    0.0   0.0    0.0    0.0  0.0   0.0   0.0   0.0    0.0
fD   0.0    0.0   0.0    0.0    0.0  0.0   0.0   0.0   0.0    0.0
fE   0.0    0.0   0.0    0.0    0.0  0.0   0.0   0.0   0.0    0.0

The transported amounts of product pC from warehouse to store:

,sA,sB,sC,sD,sE,sF,sG,sH,sI,sJ,sK,sL,sM,sN,sO,sP,sQ,sR,sS,sT
wA,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wB,0.0,0.0,30.0,70.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wC,0.0,0.0,0.0,0.0,30.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wD,0.0,0.0,0.0,0.0,0.0,0.0,50.0,60.0,0.0,110.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,0.0,100.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0
wH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,20.0,0.0,0.0,0.0,0.0
wI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,40.0,0.0,0.0
wJ,80.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60.0,70.0

The transported amounts of product pD from factory to warehouse:

     wA    wB    wC    wD     wE   wF    wG    wH    wI     wJ
fA  0.0   0.0   0.0   0.0    0.0  0.0   0.0   0.0   0.0    0.0
fB  0.0   0.0   0.0   0.0    0.0  0.0   0.0   0.0   0.0    0.0
fC  0.0   0.0   0.0   0.0    0.0  0.0   0.0   0.0   0.0    0.0
fD  0.0  60.0  30.0  70.0  140.0  0.0   0.0   0.0   0.0    0.0
fE  0.0   0.0   0.0   0.0    0.0  0.0  50.0  50.0  40.0  140.0

The transported amounts of product pD from warehouse to store:

,sA,sB,sC,sD,sE,sF,sG,sH,sI,sJ,sK,sL,sM,sN,sO,sP,sQ,sR,sS,sT
wA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wB,0.0,0.0,20.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wC,0.0,0.0,0.0,0.0,10.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wD,0.0,0.0,0.0,0.0,0.0,0.0,30.0,40.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,50.0,50.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0
wH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40.0,10.0,0.0,0.0,0.0,0.0
wI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,20.0,0.0,0.0
wJ,40.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,60.0

The transported amounts of product pE from factory to warehouse:

       wA     wB     wC     wD     wE   wF     wG     wH     wI     wJ
fA    0.0    0.0    0.0    0.0    0.0  0.0    0.0    0.0    0.0    0.0
fB    0.0    0.0    0.0    0.0    0.0  0.0    0.0    0.0    0.0    0.0
fC  420.0  450.0  530.0    0.0    0.0  0.0    0.0    0.0    0.0    0.0
fD    0.0    0.0    0.0  210.0  790.0  0.0    0.0    0.0    0.0    0.0
fE    0.0    0.0    0.0    0.0  290.0  0.0  340.0  380.0  230.0  520.0

The transported amounts of product pE from warehouse to store:

,sA,sB,sC,sD,sE,sF,sG,sH,sI,sJ,sK,sL,sM,sN,sO,sP,sQ,sR,sS,sT
wA,220.0,200.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wB,0.0,0.0,150.0,300.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wC,0.0,0.0,0.0,0.0,140.0,150.0,240.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wD,0.0,0.0,0.0,0.0,0.0,0.0,0.0,210.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,180.0,390.0,360.0,150.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
wG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,140.0,200.0,0.0,0.0,0.0,0.0,0.0,0.0
wH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,250.0,130.0,0.0,0.0,0.0,0.0
wI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,130.0,100.0,0.0,0.0
wJ,80.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,210.0,230.0

# Swimmers

Instead of using dictionaries we'll show how store the coefficient in pandas series and data frames in this example.  They're convenient as long as the data is one or two dimensional.

In [49]:
import pandas as pd

swimmers = ['Carl', 'Chris', 'David', 'Tony', 'Ken']
supply = pd.Series([1, 1, 1, 1, 1], index=swimmers)

# use a dummy stroke to balance the problem
strokes = ['backstroke', 'breaststroke', 'butterfly', 'freestyle', 'no_swim']
demand = pd.Series([1, 1, 1, 1, 1], index=strokes)

times = [
    [37.7, 43.4, 33.3, 29.2, 0],
    [32.9, 33.1, 28.5, 26.4, 0],
    [33.8, 42.2, 38.9, 29.6, 0],
    [37.0, 34.7, 30.4, 28.5, 0],
    [35.4, 41.8, 33.6, 31.1, 0],
]
times_df = pd.DataFrame(times, index=swimmers, columns=strokes)

from pyomo.environ import *

model = ConcreteModel()

#decision vars
model.assign = Var(swimmers, strokes, domain=NonNegativeReals)

#objective function
model.relay_time = Objective(expr=sum(times_df.loc[sw, st] *
                                      model.assign[sw, st] for sw in swimmers
                                      for st in strokes),
                             sense=minimize)

#constraints
model.supply_ct = ConstraintList()
for sw in swimmers:
    model.supply_ct.add(sum(model.assign[sw, st] for st in strokes) == supply[sw])

model.demand_ct = ConstraintList()
for st in strokes:
    model.demand_ct.add(sum(model.assign[sw, st] for sw in swimmers) == demand[st])

# solve and display
solver = SolverFactory('glpk')
solver.solve(model)

# display solution
print("Fastest relay time is {:.1f} seconds".format(model.relay_time()))
best_race = pd.DataFrame([[int(model.assign[sw, st]()) for st in strokes] for sw in swimmers],
                     index=swimmers,
                     columns=strokes)
print("Swimmer stroke assignments:")
best_race

Fastest relay time is 126.2 seconds
Swimmer stroke assignments:

       backstroke  breaststroke  butterfly  freestyle  no_swim
Carl            0             0          0          1        0
Chris           0             0          1          0        0
David           1             0          0          0        0
Tony            0             1          0          0        0
Ken             0             0          0          0        1